import {
  makeConstant
} from "../../utils";
const STATE_BRANCH = 'MOCS';
const makeMocConstant = (type) => makeConstant(STATE_BRANCH, type);

export const GET_MOCS = makeMocConstant('GET_MOCS');
export const GET_MOCS_SUCCESS = "GET_MOCS_SUCCESS";
export const GET_MOCS_FAILED = "GET_MOCS_FAILED";
export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const ADD_CANDIDATE_SUCCESS = 'ADD_CANDIDATE_SUCCESS';
export const ADD_CANDIDATE_FAILURE = 'ADD_CANDIDATE_FAILURE';
export const GET_CONGRESS_BY_SESSION = makeMocConstant('GET_CONGRESS_BY_SESSION');
export const GET_CONGRESS_BY_SESSION_SUCCESS = makeMocConstant('GET_CONGRESS_BY_SESSION_SUCCESS');
export const GET_CONGRESS_BY_SESSION_FAILED = makeMocConstant('GET_CONGRESS_BY_SESSION_FAILED');
export const UPDATE_MISSING_MEMBER = makeMocConstant('UPDATE_MISSING_MEMBER');
export const UPDATE_MISSING_MEMBER_SUCCESS = makeMocConstant('UPDATE_MISSING_MEMBER_SUCCESS');
export const UPDATE_MISSING_MEMBER_FAIL = makeMocConstant('UPDATE_MISSING_MEMBER_FAIL');
export const UPDATE_IN_OFFICE = makeMocConstant('UPDATE_IN_OFFICE');
export const UPDATE_IN_OFFICE_SUCCESS = makeMocConstant('UPDATE_IN_OFFICE_SUCCESS');
export const UPDATE_IN_OFFICE_FAIL = makeMocConstant('UPDATE_IN_OFFICE_FAIL');
export const UPDATE_DISPLAY_NAME = makeMocConstant('UPDATE_DISPLAY_NAME');
export const UPDATE_DISPLAY_NAME_SUCCESS = makeMocConstant('UPDATE_DISPLAY_NAME_SUCCESS');
export const UPDATE_DISPLAY_NAME_FAIL = makeMocConstant('UPDATE_DISPLAY_NAME_FAIL');
export const ADD_STATE_LEG = 'ADD_STATE_LEG';
export const ADD_STATE_LEG_SUCCESS = 'ADD_STATE_LEG_SUCCESS';
export const ADD_STATE_LEG_FAILURE = 'ADD_STATE_LEG_FAILURE';
export const REQUEST_STATE_LEG = makeMocConstant('REQUEST_STATE_LEG');
export const REQUEST_STATE_LEG_SUCCESS = makeMocConstant("REQUEST_STATE_LEG_SUCCESS");
export const CHANGE_SELECTED_STATE = makeMocConstant('CHANGE_SELECTED_STATE');
export const UPDATE_CAMPAIGN_STATUS = makeMocConstant('UPDATE_CAMPAIGN_STATUS');
export const ADD_OFFICE_PERSON = makeMocConstant('ADD_OFFICE_PERSON_LOGIC');
export const SET_CURRENTLY_EDITING_PERSON = makeMocConstant('SAVE_NEW_PERSON');
export const ADD_OFFICE_TO_PERSON = makeMocConstant('ADD_OFFICE');
export const UPDATE_CURRENTLY_EDITING_PERSON = makeMocConstant('UPDATE_CURRENTLY_EDITING_PERSON');
export const CLEAR_CURRENTLY_EDITING_PERSON = makeMocConstant('CLEAR_CURRENTLY_EDITING_PERSON');
